Catch::ExceptionTranslatorRegistrar Class Reference
#include <catch.hpp>
Public Member Functions
template<typename T >
ExceptionTranslatorRegistrar (std::string(*translateFunction)(T &))
Constructor & Destructor Documentation
template<typename T > Catch::ExceptionTranslatorRegistrar::ExceptionTranslatorRegistrar (std::string(*)(T &) translateFunction) [inline]
References Catch::getCurrentContext(), Catch::IContext::getExceptionTranslatorRegistry(), and Catch::IExceptionTranslatorRegistry::registerTranslator().
The documentation for this class was generated from the following file:
include/catch.hpp