Catch::TestCaseInfo Class Reference
#include <catch.hpp>
Public Member Functions
TestCaseInfo (ITestCase *testCase, const char *name, const char *description, const SourceLineInfo &lineInfo)
TestCaseInfo ()
TestCaseInfo (const TestCaseInfo &other)
TestCaseInfo (const TestCaseInfo &other, const std::string &name)
TestCaseInfo & operator= (const TestCaseInfo &other)
~TestCaseInfo ()
void invoke () const
const std::string & getName () const
const std::string & getDescription () const
const SourceLineInfo & getLineInfo () const
bool isHidden () const
void swap (TestCaseInfo &other)
bool operator== (const TestCaseInfo &other) const
bool operator< (const TestCaseInfo &other) const
Constructor & Destructor Documentation
Catch::TestCaseInfo::TestCaseInfo (ITestCase * testCase, const char * name, const char * description, const SourceLineInfo & lineInfo) [inline]
Catch::TestCaseInfo::TestCaseInfo () [inline]
Catch::TestCaseInfo::TestCaseInfo (const TestCaseInfo & other) [inline]
Catch::TestCaseInfo::TestCaseInfo (const TestCaseInfo & other, const std::string & name) [inline]
Catch::TestCaseInfo::~TestCaseInfo () [inline]
Member Function Documentation
const std::string& Catch::TestCaseInfo::getDescription () const [inline]
const SourceLineInfo& Catch::TestCaseInfo::getLineInfo () const [inline]
const std::string& Catch::TestCaseInfo::getName () const [inline]
void Catch::TestCaseInfo::invoke () const [inline]
References Catch::ITestCase::invoke().
bool Catch::TestCaseInfo::isHidden () const [inline]
bool Catch::TestCaseInfo::operator< (const TestCaseInfo & other) const [inline]
TestCaseInfo& Catch::TestCaseInfo::operator= (const TestCaseInfo & other) [inline]
References swap().
bool Catch::TestCaseInfo::operator== (const TestCaseInfo & other) const [inline]
void Catch::TestCaseInfo::swap (TestCaseInfo & other) [inline]
References Catch::SourceLineInfo::swap().
The documentation for this class was generated from the following file:
include/catch.hpp