Catch::Section Class Reference
#include <catch.hpp>
Public Member Functions
Section (const std::string &name, const std::string &description, const SourceLineInfo &lineInfo)
~Section ()
operator bool ()
Constructor & Destructor Documentation
Catch::Section::Section (const std::string & name, const std::string & description, const SourceLineInfo & lineInfo) [inline]
Catch::Section::~Section () [inline]
References Catch::getCurrentContext(), Catch::IContext::getResultCapture(), and Catch::IResultCapture::sectionEnded().
Member Function Documentation
Catch::Section::operator bool () [inline]
The documentation for this class was generated from the following file:
include/catch.hpp