Catch::ResultInfo Class Reference
#include <catch.hpp>
Public Member Functions
ResultInfo ()
ResultInfo (const char *expr, ResultWas::OfType result, bool isNot, const SourceLineInfo &lineInfo, const char *macroName, const char *message)
virtual ~ResultInfo ()
bool ok () const
ResultWas::OfType getResultType () const
bool hasExpression () const
bool hasMessage () const
std::string getExpression () const
bool hasExpandedExpression () const
std::string getExpandedExpression () const
std::string getMessage () const
std::string getFilename () const
std::size_t getLine () const
std::string getTestMacroName () const
Protected Member Functions
std::string getExpandedExpressionInternal () const
bool isNotExpression (const char *expr)
Protected Attributes
std::string m_macroName
SourceLineInfo m_lineInfo
std::string m_expr
std::string m_lhs
std::string m_rhs
std::string m_op
std::string m_message
ResultWas::OfType m_result
bool m_isNot
Constructor & Destructor Documentation
Catch::ResultInfo::ResultInfo () [inline]
Catch::ResultInfo::ResultInfo (const char * expr, ResultWas::OfType result, bool isNot, const SourceLineInfo & lineInfo, const char * macroName, const char * message) [inline]
References m_expr.
virtual Catch::ResultInfo::~ResultInfo () [inline], [virtual]
Member Function Documentation
std::string Catch::ResultInfo::getExpandedExpression () const [inline]
References getExpandedExpressionInternal(), and hasExpression().
std::string Catch::ResultInfo::getExpandedExpressionInternal () const [inline], [protected]
References m_expr, m_isNot, m_lhs, m_macroName, m_op, and m_rhs.
std::string Catch::ResultInfo::getExpression () const [inline]
References m_expr.
std::string Catch::ResultInfo::getFilename () const [inline]
References Catch::SourceLineInfo::file, and m_lineInfo.
std::size_t Catch::ResultInfo::getLine () const [inline]
References Catch::SourceLineInfo::line, and m_lineInfo.
std::string Catch::ResultInfo::getMessage () const [inline]
References m_message.
ResultWas::OfType Catch::ResultInfo::getResultType () const [inline]
References m_result.
std::string Catch::ResultInfo::getTestMacroName () const [inline]
References m_macroName.
bool Catch::ResultInfo::hasExpandedExpression () const [inline]
References getExpandedExpressionInternal(), hasExpression(), and m_expr.
bool Catch::ResultInfo::hasExpression () const [inline]
References m_expr.
bool Catch::ResultInfo::hasMessage () const [inline]
References m_message.
bool Catch::ResultInfo::isNotExpression (const char * expr) [inline], [protected]
bool Catch::ResultInfo::ok () const [inline]
References Catch::ResultWas::FailureBit, and m_result.
Member Data Documentation
std::string Catch::ResultInfo::m_expr [protected]
bool Catch::ResultInfo::m_isNot [protected]
std::string Catch::ResultInfo::m_lhs [protected]
SourceLineInfo Catch::ResultInfo::m_lineInfo [protected]
std::string Catch::ResultInfo::m_macroName [protected]
std::string Catch::ResultInfo::m_message [protected]
std::string Catch::ResultInfo::m_op [protected]
ResultWas::OfType Catch::ResultInfo::m_result [protected]
std::string Catch::ResultInfo::m_rhs [protected]
The documentation for this class was generated from the following file:
include/catch.hpp