traffic_engineering.Cycle Class Reference
Public Member Functions
def __init__
def computeCriticalCharges
def computeOptimalCycle
def computeMinimumCycle
def computeEffectiveGreen
Public Attributes
phases
lostTime
saturationVolume
criticalCharges
criticalCharge
C
effectiveGreens
Detailed Description
Class to compute optimal cycle and the split of effective green times
Constructor & Destructor Documentation
def traffic_engineering.Cycle.__init__ (self, phases, lostTime, saturationVolume)
phases is a list of phases
a phase is a list of lanegroups
Member Function Documentation
def traffic_engineering.Cycle.computeCriticalCharges (self)
def traffic_engineering.Cycle.computeEffectiveGreen (self)
References traffic_engineering.Cycle.C, and traffic_engineering.Cycle.lostTime.
def traffic_engineering.Cycle.computeMinimumCycle (self, degreeSaturation = 1.)
References traffic_engineering.Cycle.C, traffic_engineering.Cycle.computeCriticalCharges(), traffic_engineering.Cycle.criticalCharge, traffic_engineering.Cycle.lostTime, and traffic_engineering.minimumCycle().
def traffic_engineering.Cycle.computeOptimalCycle (self)
References traffic_engineering.Cycle.computeCriticalCharges().
Member Data Documentation
traffic_engineering.Cycle.C
traffic_engineering.Cycle.criticalCharge
traffic_engineering.Cycle.criticalCharges
traffic_engineering.Cycle.effectiveGreens
traffic_engineering.Cycle.lostTime
traffic_engineering.Cycle.phases
traffic_engineering.Cycle.saturationVolume
The documentation for this class was generated from the following file:
python/traffic_engineering.py