Catch::CompositeGenerator< T > Class Template Reference
#include <catch.hpp>
Public Member Functions
CompositeGenerator ()
CompositeGenerator (CompositeGenerator &other)
CompositeGenerator & setFileInfo (const char *fileInfo)
~CompositeGenerator ()
operator T () const
void add (const IGenerator< T > *generator)
CompositeGenerator & then (CompositeGenerator &other)
CompositeGenerator & then (T value)
Constructor & Destructor Documentation
template<typename T> Catch::CompositeGenerator< T >::CompositeGenerator () [inline]
template<typename T> Catch::CompositeGenerator< T >::CompositeGenerator (CompositeGenerator< T > & other) [inline]
template<typename T> Catch::CompositeGenerator< T >::~CompositeGenerator () [inline]
References Catch::deleteAll().
Member Function Documentation
template<typename T> void Catch::CompositeGenerator< T >::add (const IGenerator< T > * generator) [inline]
References Catch::IGenerator< T >::size().
template<typename T> Catch::CompositeGenerator< T >::operator T () const [inline]
References CATCH_INTERNAL_ERROR, Catch::getCurrentContext(), Catch::IContext::getGeneratorIndex(), Catch::IGenerator< T >::getValue(), and Catch::IGenerator< T >::size().
template<typename T> CompositeGenerator& Catch::CompositeGenerator< T >::setFileInfo (const char * fileInfo) [inline]
template<typename T> CompositeGenerator& Catch::CompositeGenerator< T >::then (CompositeGenerator< T > & other) [inline]
template<typename T> CompositeGenerator& Catch::CompositeGenerator< T >::then (T value) [inline]
References Catch::ValuesGenerator< T >::add(), and Catch::CompositeGenerator< T >::add().
The documentation for this class was generated from the following file:
include/catch.hpp