Catch::ExpressionBuilder Class Reference
#include <catch.hpp>
Public Member Functions
ExpressionBuilder (const SourceLineInfo &lineInfo, const char *macroName, const char *expr=``, bool isNot=false)
template<typename T >
Expression< const T & > operator->* (const T &operand)
Expression< bool > operator->* (bool value)
template<typename T >
ExpressionBuilder & operator<< (const T &value)
template<typename MatcherT , typename ArgT >
ExpressionBuilder & acceptMatcher (const MatcherT &matcher, const ArgT &arg, const std::string &matcherCallAsString)
template<typename MatcherT , typename ArgT >
ExpressionBuilder & acceptMatcher (const MatcherT &matcher, ArgT *arg, const std::string &matcherCallAsString)
ExpressionBuilder & setResultType (ResultWas::OfType resultType)
operator ResultInfoBuilder & ()
Constructor & Destructor Documentation
Catch::ExpressionBuilder::ExpressionBuilder (const SourceLineInfo & lineInfo, const char * macroName, const char * expr = ``, bool isNot = false) [inline]
Member Function Documentation
template<typename MatcherT , typename ArgT > ExpressionBuilder& Catch::ExpressionBuilder::acceptMatcher (const MatcherT & matcher, const ArgT & arg, const std::string & matcherCallAsString) [inline]
References Catch::ResultWas::ExpressionFailed, Catch::ResultWas::Ok, Catch::ResultInfoBuilder::setLhs(), Catch::ResultInfoBuilder::setOp(), Catch::ResultInfoBuilder::setResultType(), Catch::ResultInfoBuilder::setRhs(), and Catch::toString().
template<typename MatcherT , typename ArgT > ExpressionBuilder& Catch::ExpressionBuilder::acceptMatcher (const MatcherT & matcher, ArgT * arg, const std::string & matcherCallAsString) [inline]
References Catch::ResultWas::ExpressionFailed, Catch::ResultWas::Ok, Catch::ResultInfoBuilder::setLhs(), Catch::ResultInfoBuilder::setOp(), Catch::ResultInfoBuilder::setResultType(), Catch::ResultInfoBuilder::setRhs(), and Catch::toString().
Catch::ExpressionBuilder::operator ResultInfoBuilder & () [inline]
References Catch::ResultInfoBuilder::setMessage().
template<typename T > Expression<const T&> Catch::ExpressionBuilder::operator->* (const T & operand) [inline]
Expression<bool> Catch::ExpressionBuilder::operator->* (bool value) [inline]
template<typename T > ExpressionBuilder& Catch::ExpressionBuilder::operator<< (const T & value) [inline]
References Catch::toString().
ExpressionBuilder& Catch::ExpressionBuilder::setResultType (ResultWas::OfType resultType) [inline]
References Catch::ResultInfoBuilder::setResultType().
The documentation for this class was generated from the following file:
include/catch.hpp