Catch::ScopedInfo Class Reference
#include <catch.hpp>
Public Member Functions
ScopedInfo ()
~ScopedInfo ()
template<typename T >
ScopedInfo & operator<< (const T &value)
std::string getInfo () const
Constructor & Destructor Documentation
Catch::ScopedInfo::ScopedInfo () [inline]
References Catch::getCurrentContext(), Catch::IContext::getResultCapture(), and Catch::IResultCapture::pushScopedInfo().
Catch::ScopedInfo::~ScopedInfo () [inline]
References Catch::getCurrentContext(), Catch::IContext::getResultCapture(), and Catch::IResultCapture::popScopedInfo().
Member Function Documentation
std::string Catch::ScopedInfo::getInfo () const [inline]
template<typename T > ScopedInfo& Catch::ScopedInfo::operator<< (const T & value) [inline]
The documentation for this class was generated from the following file:
include/catch.hpp