indicators.LCSS Class Reference
Public Member Functions
def __init__
def checkIndicator
def compute
def computeNormalized
def computeDistance
Public Attributes
minLength
Detailed Description
Adapted LCSS class for indicators, same pattern
Constructor & Destructor Documentation
def indicators.LCSS.__init__ (self, similarityFunc, delta = float('inf'), minLength = 0, aligned = False, lengthFunc = min)
Member Function Documentation
def indicators.LCSS.checkIndicator (self, indicator)
References indicators.LCSS.minLength.
def indicators.LCSS.compute (self, indicator1, indicator2, computeSubSequence = False)
References indicators.LCSS.checkIndicator().
def indicators.LCSS.computeDistance (self, indicator1, indicator2, computeSubSequence = False)
References indicators.LCSS.checkIndicator().
def indicators.LCSS.computeNormalized (self, indicator1, indicator2, computeSubSequence = False)
References indicators.LCSS.checkIndicator().
Member Data Documentation
indicators.LCSS.minLength
The documentation for this class was generated from the following file:
python/indicators.py