Catch::Detail::Approx Class Reference
#include <catch.hpp>
Public Member Functions
Approx (double value)
Approx (const Approx &other)
Approx operator() (double value)
Approx & epsilon (double newEpsilon)
Approx & scale (double newScale)
std::string toString () const
Static Public Member Functions
static Approx custom ()
Friends
bool operator== (double lhs, const Approx &rhs)
bool operator== (const Approx &lhs, double rhs)
bool operator!= (double lhs, const Approx &rhs)
bool operator!= (const Approx &lhs, double rhs)
Constructor & Destructor Documentation
Catch::Detail::Approx::Approx (double value) [inline], [explicit]
Catch::Detail::Approx::Approx (const Approx & other) [inline]
Member Function Documentation
static Approx Catch::Detail::Approx::custom () [inline], [static]
References Approx().
Approx& Catch::Detail::Approx::epsilon (double newEpsilon) [inline]
Approx Catch::Detail::Approx::operator() (double value) [inline]
References epsilon(), and scale().
Approx& Catch::Detail::Approx::scale (double newScale) [inline]
std::string Catch::Detail::Approx::toString () const [inline]
Friends And Related Function Documentation
bool operator!= (double lhs, const Approx & rhs) [friend]
bool operator!= (const Approx & lhs, double rhs) [friend]
bool operator== (double lhs, const Approx & rhs) [friend]
bool operator== (const Approx & lhs, double rhs) [friend]
The documentation for this class was generated from the following file:
include/catch.hpp