traffic_engineering.FundamentalDiagram Class Reference
Public Member Functions
def __init__
def q
def plotVK
def plotQK
Static Public Member Functions
def meanHeadway
def meanSpacing
Public Attributes
name
Detailed Description

Constructor & Destructor Documentation
def traffic_engineering.FundamentalDiagram.__init__ (self, name)
Member Function Documentation
def traffic_engineering.FundamentalDiagram.meanHeadway (k) [static]
def traffic_engineering.FundamentalDiagram.meanSpacing (q) [static]
def traffic_engineering.FundamentalDiagram.plotQK (self, language = 'fr', units = {})
References traffic_engineering.GreenbergFD.kj, and traffic_engineering.FundamentalDiagram.q().
def traffic_engineering.FundamentalDiagram.plotVK (self, language = 'fr', units = {})
References traffic_engineering.GreenbergFD.kj, and traffic_engineering.GreenbergFD.v().
def traffic_engineering.FundamentalDiagram.q (self, k)
References traffic_engineering.GreenbergFD.v().
Member Data Documentation
traffic_engineering.FundamentalDiagram.name
The documentation for this class was generated from the following file:
python/traffic_engineering.py