c/feature-based-tracking.cpp File Reference
#include `Motion.hpp`
*
#include `Parameters.hpp`
*
#include `cvutils.hpp`
*
#include `utils.hpp`
*
#include `src/Trajectory.h`
*
#include `src/TrajectoryDBAccessList.h`
*
#include `src/TrajectoryDBAccessBlob.h`
*
#include `opencv2/core/core.hpp`
*
#include `opencv2/imgproc/imgproc.hpp`
*
#include `opencv2/video/tracking.hpp`
*
#include `opencv2/features2d/features2d.hpp`
*
#include `opencv2/highgui/highgui.hpp`
*
#include `opencv2/objdetect/objdetect.hpp`
*
#include <boost/foreach.hpp>
*
#include <iostream>
*
#include <vector>
*
#include <ctime>
*
#include <cmath>
*
#include <memory>
*
#include <limits>
*
Classes
struct FeaturePointMatch
Functions
void drawMatchesRelative (const vector< KeyPoint > &train, const vector< KeyPoint > &query, std::vector< cv::DMatch > &matches, Mat &img)
void drawOpticalFlow (const vector< Point2f > &prevPts, const vector< Point2f > &currPts, const vector< uchar > status, Mat &img)
void saveFeatures (vector< FeatureTrajectoryPtr > &features, TrajectoryDBAccess< Point2f > &db, const string &positionsTableName, const string &velocitiesTableName)
void trackFeatures (const KLTFeatureTrackingParameters &params)
void groupFeatures (const KLTFeatureTrackingParameters &params)
void loadingTimes (const KLTFeatureTrackingParameters &params)
int main (int argc, char *argv[])
Function Documentation
void drawMatchesRelative (const vector< KeyPoint > & train, const vector< KeyPoint > & query, std::vector< cv::DMatch > & matches, Mat & img)
void drawOpticalFlow (const vector< Point2f > & prevPts, const vector< Point2f > & currPts, const vector< uchar > status, Mat & img)
void groupFeatures (const KLTFeatureTrackingParameters & params)
References FeatureGraph::addFeature(), FeatureGraph::connectedComponents(), KLTFeatureTrackingParameters::databaseFilename, display-trajectories::firstFrameNum, KLTFeatureTrackingParameters::frame1, classify-objects::frameNum, FeatureGraph::getFeatureGroups(), FeatureGraph::informationString(), classify-objects::lastFrameNum, KLTFeatureTrackingParameters::minFeatureTime, KLTFeatureTrackingParameters::minNFeaturesPerGroup, KLTFeatureTrackingParameters::mmConnectionDistance, KLTFeatureTrackingParameters::mmSegmentationDistance, and KLTFeatureTrackingParameters::nFrames.
void loadingTimes (const KLTFeatureTrackingParameters & params)
References KLTFeatureTrackingParameters::databaseFilename, and learn-motion-patterns::trajectories.
int main (int argc, char * argv[])
References KLTFeatureTrackingParameters::groupFeatures, groupFeatures(), KLTFeatureTrackingParameters::loadingTime, loadingTimes(), KLTFeatureTrackingParameters::parameterDescription, classify-objects::params, KLTFeatureTrackingParameters::trackFeatures, and trackFeatures().
void saveFeatures (vector< FeatureTrajectoryPtr > & features, TrajectoryDBAccess< Point2f > & db, const string & positionsTableName, const string & velocitiesTableName) [inline]
References compute-homography::f.
void trackFeatures (const KLTFeatureTrackingParameters & params)
Todo
Todo try calcOpticalFlowFarneback
References KLTFeatureTrackingParameters::accelerationBound, KLTFeatureTrackingParameters::blockSize, classify-objects::capture, KLTFeatureTrackingParameters::databaseFilename, KLTFeatureTrackingParameters::deviationBound, KLTFeatureTrackingParameters::display, KLTFeatureTrackingParameters::distortionCoefficients, compute-homography::f, FeaturePointMatch::feature, KLTFeatureTrackingParameters::featureQuality, KLTFeatureTrackingParameters::frame1, classify-objects::frameNum, compute-clearmot::homography, KLTFeatureTrackingParameters::homographyFilename, KLTFeatureTrackingParameters::interpolationMethod, interruptionKey(), KLTFeatureTrackingParameters::intrinsicCameraFilename, display-trajectories::intrinsicCameraMatrix, classify-objects::invHomography, KLTFeatureTrackingParameters::k, classify-objects::lastFrameNum, loadMat(), compute-clearmot::mask, KLTFeatureTrackingParameters::maskFilename, KLTFeatureTrackingParameters::maxNFeatures, KLTFeatureTrackingParameters::maxNumberTrackingIterations, KLTFeatureTrackingParameters::minFeatureDisplacement, KLTFeatureTrackingParameters::minFeatureDistanceKLT, KLTFeatureTrackingParameters::minFeatureEigThreshold, KLTFeatureTrackingParameters::minFeatureTime, KLTFeatureTrackingParameters::minTrackingError, KLTFeatureTrackingParameters::nDisplacements, KLTFeatureTrackingParameters::nFrames, KLTFeatureTrackingParameters::nFramesSmoothing, KLTFeatureTrackingParameters::pyramidLevel, Colors::red(), saveFeatures(), KLTFeatureTrackingParameters::undistort, KLTFeatureTrackingParameters::undistortedImageMultiplication, KLTFeatureTrackingParameters::useHarrisDetector, KLTFeatureTrackingParameters::videoFilename, and KLTFeatureTrackingParameters::windowSize.