cvutils Namespace Reference
Functions
def quitKey
def saveKey
def int2FOURCC
def plotLines
def rgb2gray
def matlab2PointCorrespondences
def loadPointCorrespondences
def cvMatToArray
def computeHomography
def arrayToCvMat
def cvPlot
def cvImshow
def computeUndistortMaps
def playVideo
def infoVideo
def getImagesFromVideo
def getFPS
def imageBox
def displayTrajectories
def computeHomographyFromPDTV
def undistortedCoordinates
def undistortTrajectoryFromCVMapping
def computeInverseMapping
def cameraIntrinsicCalibration
def undistortImage
def printCvMat
def projectArray
def project
def projectTrajectory
def invertHomography
def undistortTrajectory
def projectGInputPoints
def computeTranslation
def HOG
def createHOGTrainingSet
Variables
opencvAvailable = True
skimageAvailable = True
tuple cvRed = (0,0,255)
tuple cvGreen = (0,255,0)
tuple cvBlue = (255,0,0)
tuple cvCyan = (255, 255, 0)
tuple cvYellow = (0, 255, 255)
tuple cvMagenta = (255, 0, 255)
tuple cvWhite = (255, 255, 255)
tuple cvBlack = (0,0,0)
tuple cvColors3
tuple cvColors
Function Documentation
def cvutils.arrayToCvMat (a, t = cv2.CV_64FC1)
Converts a numpy array to an OpenCV CvMat, with default type CV_64FC1.
def cvutils.cameraIntrinsicCalibration (path, checkerBoardSize = [6, secondPassSearch = False, display = False)
Camera calibration searches through all the images (jpg or png) located
    in _path_ for matches to a checkerboard pattern of size checkboardSize.
    These images should all be of the same camera with the same resolution.

    For best results, use an asymetric board and ensure that the image has
    very high contrast, including the background. Suitable checkerboard:
    http://ftp.isr.ist.utl.pt/pub/roswiki/attachments/camera_calibration(2f)Tutorials(2f)StereoCalibration/check-108.png

    The code below is based off of:
    https://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html
    Modified by Paul St-Aubin
def cvutils.computeHomography (srcPoints, dstPoints, method = 0, ransacReprojThreshold = 3.0)
Returns the homography matrix mapping from srcPoints to dstPoints (dimension Nx2)
def cvutils.computeHomographyFromPDTV (camera)
Returns the homography matrix at ground level from PDTV camera
https://bitbucket.org/hakanardo/pdtv
def cvutils.computeInverseMapping (originalImageSize, map1, map2)
References undistortedCoordinates().
def cvutils.computeTranslation (img1, img2, img1Points, maxTranslation2, minNMatches, windowSize = (5,5, level = 5, criteria = (cv2.TERM_CRITERIA_EPS, 0)
Computes the translation of img2 with respect to img1
(loaded using OpenCV as numpy arrays)
img1Points are used to compute the translation

TODO add diagnostic if data is all over the place, and it most likely is not a translation (eg zoom, other non linear distortion)
def cvutils.computeUndistortMaps (width, height, undistortedImageMultiplication, intrinsicCameraMatrix, distortionCoefficients)
def cvutils.createHOGTrainingSet (imageDirectory, classLabel, rescaleSize = (64, 64, orientations = 9, pixelsPerCell = (8, 8, cellsPerBlock = (2, 2, visualize = False, normalize = False)
References HOG().
def cvutils.cvImshow (windowName, img, rescale = 1.0)
def cvutils.cvMatToArray (cvmat)
Converts an OpenCV CvMat to numpy array.
def cvutils.cvPlot (img, positions, color, lastCoordinate = None, kwargs)
def cvutils.displayTrajectories (videoFilename, objects, boundingBoxes = {}, homography = None, firstFrameNum = 0, lastFrameNumArg = None, printFrames = True, rescale = 1., nFramesStep = 1, saveAllImages = False, undistort = False, intrinsicCameraMatrix = None, distortionCoefficients = None, undistortedImageMultiplication = 1., annotations = [], gtMatches = {}, toMatches = {})
Displays the objects overlaid frame by frame over the video 
References computeUndistortMaps(), cvImshow(), cvPlot(), imageBox(), quitKey(), and saveKey().
def cvutils.getFPS (videoFilename)
def cvutils.getImagesFromVideo (videoFilename, firstFrameNum = 0, nFrames = 1, saveImage = False, outputPrefix = 'image')
Returns nFrames images from the video sequence
def cvutils.HOG (image, rescaleSize = (64, 64, orientations = 9, pixelsPerCell = (8, 8, cellsPerBlock = (2, 2, visualize = False, normalize = False)
def cvutils.imageBox (img, obj, frameNum, homography, width, height, px = 0.2, py = 0.2, minNPixels = 800)
References project().
def cvutils.infoVideo (filename)
Provides all available info on video 
References int2FOURCC().
def cvutils.int2FOURCC (x)
def cvutils.invertHomography (homography)
Returns an inverted homography
Unnecessary for reprojection over camera image
def cvutils.loadPointCorrespondences (filename)
Loads and returns the corresponding points in world (first 2 lines) and image spaces (last 2 lines)
def cvutils.matlab2PointCorrespondences (filename)
Loads and converts the point correspondences saved 
by the matlab camera calibration tool
def cvutils.playVideo (filename, firstFrameNum = 0, frameRate = -1, interactive = False, printFrames = True, text = None, rescale = 1., step = 1)
Plays the video
References cvImshow(), quitKey(), and saveKey().
def cvutils.plotLines (filename, origins, destinations, w = 1, resultFilename = 'image.png')
Draws lines over the image 
def cvutils.printCvMat (cvmat, out = stdout)
Prints the cvmat to out
def cvutils.project (homography, p)
Returns the coordinates of the projection of the point p with coordinates p[0], p[1]
through homography
References projectArray().
def cvutils.projectArray (homography, points)
Returns the coordinates of the projected points through homography
(format: array 2xN points)
def cvutils.projectGInputPoints (homography, points)
References projectTrajectory().
def cvutils.projectTrajectory (homography, trajectory)
Projects a series of points in the format
[[x1, x2, ...],
[y1, y2, ...]]
References projectArray().
def cvutils.quitKey (key)
def cvutils.rgb2gray (rgb)
def cvutils.saveKey (key)
def cvutils.undistortedCoordinates (map1, map2, x, y, maxDistance = 1.)
Returns the coordinates of a point in undistorted image
map1 and map2 are the mapping functions from undistorted image
to distorted (original image)
map1(x,y) = originalx, originaly
def cvutils.undistortImage (img, intrinsicCameraMatrix = None, distortionCoefficients = None, undistortedImageMultiplication = 1., interpolation = cv2.INTER_LINEAR)
Undistorts the image passed in argument
References computeUndistortMaps().
def cvutils.undistortTrajectory (invMap1, invMap2, positions)
def cvutils.undistortTrajectoryFromCVMapping (map1, map2, t)
test 'perfect' inversion
References undistortedCoordinates().
Variable Documentation
tuple cvutils.cvBlack = (0,0,0)
tuple cvutils.cvBlue = (255,0,0)
tuple cvutils.cvColors
Initial value:
= utils.PlottingPropertyValues([cvRed,
                                         cvGreen,
                                         cvBlue,
                                         cvCyan,
                                         cvYellow,
                                         cvMagenta,
                                         cvWhite,
                                         cvBlack])
tuple cvutils.cvColors3
Initial value:
= utils.PlottingPropertyValues([cvRed,
                                          cvGreen,
                                          cvBlue])
tuple cvutils.cvCyan = (255, 255, 0)
tuple cvutils.cvGreen = (0,255,0)
tuple cvutils.cvMagenta = (255, 0, 255)
tuple cvutils.cvRed = (0,0,255)
tuple cvutils.cvWhite = (255, 255, 255)
tuple cvutils.cvYellow = (0, 255, 255)
cvutils.opencvAvailable = True
cvutils.skimageAvailable = True