performance-db Namespace Reference
Functions
def selectTrajectoryIdInstant
test query tmp trajectory instant table
def test2Setup
def selectTrajectories
test query positions/velocities in feature grouping
def dropIndices
def test1Positions
Variables
list dbFilename = sys.argv[1]
tuple connection = sqlite3.connect(dbFilename)
tuple nFeatures = storage.getNumberRowsTable(connection, `positions`, `trajectory_id`)
Function Documentation
def performance-db.dropIndices (connection)
def performance-db.selectTrajectories (connection, nFeatures)
test query positions/velocities in feature grouping
def performance-db.selectTrajectoryIdInstant (connection, lastInstant)
test query tmp trajectory instant table
def performance-db.test1Positions ()
References storage.createIndex(), and dropIndices().
def performance-db.test2Setup (connection)
References storage.getMinMax().
Variable Documentation
tuple performance-db.connection = sqlite3.connect(dbFilename)
string performance-db.dbFilename = sys.argv[1]
tuple performance-db.nFeatures = storage.getNumberRowsTable(connection, `positions`, `trajectory_id`)