moving Namespace Reference
Classes
class Interval
class TimeInterval
class STObject
class Point
class NormAngle
class FlowVector
class Trajectory
class CurvilinearTrajectory
class MovingObject
class BBAnnotation
Functions
def pointsInPolygon
def subsec_spline_dist
def ppldb2p
def getSYfromXY
def getXYfromSY
def predictPositionNoLimit
def predictPosition
def intersection
def segmentIntersection
def segmentLineIntersection
def computeClearMOT
def plotRoadUsers
Variables
shapelyAvailable = True
list userTypeNames
tuple userType2Num = utils.inverseEnumeration(userTypeNames)
tuple suite = doctest.DocFileSuite('tests/moving.txt')
Function Documentation
def moving.computeClearMOT (annotations, objects, matchingDistance, firstInstant, lastInstant, returnMatches = False, debug = False)
Computes the CLEAR MOT metrics 

Reference:
Keni, Bernardin, and Stiefelhagen Rainer. "Evaluating multiple object tracking performance: the CLEAR MOT metrics." EURASIP Journal on Image and Video Processing 2008 (2008)

objects and annotations are supposed to in the same space
current implementation is BBAnnotations (bounding boxes)
mathingDistance is threshold on matching between annotation and object

TO: tracker output (objects)
GT: ground truth (annotations)

Output: returns motp, mota, mt, mme, fpt, gt
mt number of missed GT.frames (sum of the number of GT not detected in each frame)
mme number of mismatches
fpt number of false alarm.frames (tracker objects without match in each frame)
gt number of GT.frames

if returnMatches is True, return as 2 new arguments the GT and TO matches
matches is a dict
matches[i] is the list of matches for GT/TO i
the list of matches is a dict, indexed by time, for the TO/GT id matched at time t 
(an instant t not present in matches[i] at which GT/TO exists means a missed detection or false alarm)

TODO: Should we use the distance as weights or just 1/0 if distance below matchingDistance?
(add argument useDistanceForWeights = False)
def moving.getSYfromXY (p, splines, goodEnoughSplineDistance = 0.5)
Snap a point p to it's nearest subsegment of it's nearest spline (from the list splines). A spline is a list of points (class Point), most likely a trajectory. 
    
Output:
=======
[spline index, 
subsegment leading point index, 
snapped point, 
subsegment distance, 
spline distance,
orthogonal point offset]

or None
References utils.inBetween(), and ppldb2p().
def moving.getXYfromSY (s, y, splineNum, splines, mode = 0)
Find X,Y coordinate from S,Y data. 
if mode = 0 : return Snapped X,Y
if mode !=0 : return Real X,Y
References subsec_spline_dist().
def moving.intersection (p1, p2, p3, p4)
Intersection point (x,y) of lines formed by the vectors p1-p2 and p3-p4
    http://paulbourke.net/geometry/pointlineplane/
def moving.plotRoadUsers (objects, colors)
Colors is a PlottingPropertyValues instance
def moving.pointsInPolygon (points, polygon)
Optimized tests of a series of points within (Shapely) polygon 
def moving.ppldb2p (qx, qy, p0x, p0y, p1x, p1y)
Point-projection (Q) on line defined by 2 points (P0,P1). 
    http://cs.nyu.edu/~yap/classes/visual/03s/hw/h2/math.pdf
def moving.predictPosition (position, speedOrientation, control, maxSpeed = None)
Predicts the position (moving.Point) at the next time step with given control input (deltaSpeed, deltaTheta)
speedOrientation is the other encoding of velocity, (speed, orientation)
speedOrientation and control are NormAngle
def moving.predictPositionNoLimit (nTimeSteps, initialPosition, initialVelocity, initialAcceleration = Point(0,0)
Predicts the position in nTimeSteps at constant speed/acceleration
def moving.segmentIntersection (p1, p2, p3, p4)
Returns the intersecting point of the segments [p1, p2] and [p3, p4], None otherwise
References utils.inBetween(), and intersection().
def moving.segmentLineIntersection (p1, p2, p3, p4)
Indicates if the line going through p1 and p2 intersects inside p3, p4
References utils.inBetween(), and intersection().
def moving.subsec_spline_dist (splines)
Prepare list of spline subsegments from a spline list. 

Output:
=======
ss_spline_d[spline #][mode][station]

where:
    mode=0: incremental distance
    mode=1: cumulative distance
    mode=2: cumulative distance with trailing distance
References utils.pointDistanceL2().
Variable Documentation
moving.shapelyAvailable = True
tuple moving.suite = doctest.DocFileSuite('tests/moving.txt')
tuple moving.userType2Num = utils.inverseEnumeration(userTypeNames)
list moving.userTypeNames
Initial value:
= ['unknown',
                 'car',
                 'pedestrian',
                 'motorcycle',
                 'bicycle',
                 'bus',
                 'truck']