prediction Namespace Reference
Classes
class PredictedTrajectory
class PredictedTrajectoryConstant
class PredictedTrajectoryPrototype
class PredictedTrajectoryRandomControl
class SafetyPoint
class PredictionParameters
class ConstantPredictionParameters
class NormalAdaptationPredictionParameters
class PointSetPredictionParameters
class EvasiveActionPredictionParameters
class CVDirectPredictionParameters
class CVExactPredictionParameters
class PrototypePredictionParameters
Functions
def findNearestParams
def computeCollisionTime
def savePredictedTrajectoriesFigure
def calculateProbability
def findPrototypes
def findPrototypesSpeed
def getPrototypeTrajectory
def computeCrossingsCollisionsAtInstant
Variables
tuple suite = doctest.DocFileSuite('tests/prediction.txt')
Function Documentation
def prediction.calculateProbability (nMatching, similarity, objects)
def prediction.computeCollisionTime (predictedTrajectory1, predictedTrajectory2, collisionDistanceThreshold, timeHorizon)
Computes the first instant 
at which two predicted trajectories are within some distance threshold
Computes all the times including timeHorizon

User has to check the first variable collision to know about a collision
def prediction.computeCrossingsCollisionsAtInstant (predictionParams, currentInstant, obj1, obj2, collisionDistanceThreshold, timeHorizon, computeCZ = False, debug = False, usePrototypes = False, route1 = (-1,-1, route2 = (-1,-1, prototypes = {}, secondStepPrototypes = {}, nMatching = {}, objects = [], noiseEntryNums = [], noiseExitNums = [], minSimilarity = 0.1, mostMatched = None, useDestination = True, useSpeedPrototype = True)
returns the lists of collision points and crossing zones
References computeCollisionTime(), getPrototypeTrajectory(), savePredictedTrajectoriesFigure(), and moving.segmentIntersection().
def prediction.findNearestParams (initialPosition, prototypeTrajectory)
nearest parameters are the index of minDistance and the orientation  
References moving.Point.distanceNorm2(), and moving.NormAngle.fromPoint().
def prediction.findPrototypes (prototypes, nMatching, objects, route, partialObjPositions, noiseEntryNums, noiseExitNums, minSimilarity = 0.1, mostMatched = None, spatialThreshold = 1.0, delta = 180)
behaviour prediction first step
References calculateProbability().
def prediction.findPrototypesSpeed (prototypes, secondStepPrototypes, nMatching, objects, route, partialObjPositions, noiseEntryNums, noiseExitNums, minSimilarity = 0.1, mostMatched = None, useDestination = True, spatialThreshold = 1.0, delta = 180)
References calculateProbability().
def prediction.getPrototypeTrajectory (obj, route, currentInstant, prototypes, secondStepPrototypes, nMatching, objects, noiseEntryNums, noiseExitNums, minSimilarity = 0.1, mostMatched = None, useDestination = True, useSpeedPrototype = True)
References findPrototypes(), and findPrototypesSpeed().
def prediction.savePredictedTrajectoriesFigure (currentInstant, obj1, obj2, predictedTrajectories1, predictedTrajectories2, timeHorizon)
Variable Documentation
tuple prediction.suite = doctest.DocFileSuite('tests/prediction.txt')