ubc_utils Namespace Reference
Functions
def getFileType
def isFileType
def saveTrajectoryUserTypes
def modifyTrajectoryFile
def copyTrajectoryFile
def loadTrajectories
def getFeatureNumbers
def loadInteractions
def loadCollisionPoints
Variables
list fileTypeNames
list severityIndicatorNames
list userTypeNames
list mostSevereIsMax
list ignoredValue = [None, None, None, None, None, None, -1]
Function Documentation
def ubc_utils.copyTrajectoryFile (keepTrajectory, filenameIn, filenameOut)
Reads filenameIn, keeps the trajectories for which the function keepTrajectory(trajNum, lines) is True
and writes the result in filenameOut
References storage.getLines(), and storage.openCheck().
def ubc_utils.getFeatureNumbers (objects)
def ubc_utils.getFileType (s)
def ubc_utils.isFileType (s, fileType)
def ubc_utils.loadCollisionPoints (filename, nPoints = -1)
Loads collision points and returns a dict
with keys as a pair of the numbers of the two interacting objects
References storage.getLines(), storage.openCheck(), and split().
def ubc_utils.loadInteractions (filename, nInteractions = -1)
References storage.getLines(), storage.openCheck(), and split().
def ubc_utils.loadTrajectories (filename, nObjects = -1)
Loads trajectories
References getFileType(), storage.getLines(), storage.openCheck(), and split().
def ubc_utils.modifyTrajectoryFile (modifyLines, filenameIn, filenameOut)
Reads filenameIn, replaces the lines with the result of modifyLines and writes the result in filenameOut
References storage.getLines(), and storage.openCheck().
def ubc_utils.saveTrajectoryUserTypes (inFilename, outFilename, objects)
The program saves the objects, 
by just copying the corresponding trajectory and velocity data
from the inFilename, and saving the characteristics in objects (first line)
into outFilename
References storage.getLines(), storage.openCheck(), and split().
Variable Documentation
list ubc_utils.fileTypeNames
Initial value:
= ['feature',
                 'object',
                 'prototype',
                 'contoursequence']
list ubc_utils.ignoredValue = [None, None, None, None, None, None, -1]
list ubc_utils.mostSevereIsMax
Initial value:
= [False,
                   False,
                   True,
                   True,
                   True,
                   True,
                   False]
list ubc_utils.severityIndicatorNames
Initial value:
= ['Distance',
                          'Collision Course Cosine',
                          'Velocity Cosine',
                          'Speed Differential',
                          'Collision Probability',
                          'Severity Index',
                          'Time to Collision']
list ubc_utils.userTypeNames
Initial value:
= ['car',
                 'pedestrian',
                 'twowheels',
                 'bus',
                 'truck']