storage Namespace Reference
Classes
class FakeSecHead
class ProcessParameters
Utils to read .ini type text files for configuration, meta data...
class SceneParameters
Functions
def printDBError
Sqlite.
def dropTables
def tableExists
def createIndex
def getNumberRowsTable
def getMinMax
def writeTrajectoriesToSqlite
def loadPrototypeMatchIndexesFromSqlite
def getObjectCriteria
def loadTrajectoriesFromTable
def loadUserTypesFromTable
def loadTrajectoriesFromSqlite
def savePrototypesToSqlite
def loadPrototypesFromSqlite
def loadGroundTruthFromSqlite
def deleteFromSqlite
def createInteractionTable
def createIndicatorTables
def saveInteraction
def saveInteractions
def saveIndicator
def saveIndicators
def loadInteractions
def createBoundingBoxTable
def loadBoundingBoxTableForDisplay
def writeFeaturesToSqlite
saving and loading for scene interpretation (Mohamed Gomaa Mohamed's PhD)
def writePrototypesToSqlite
def readPrototypesFromSqlite
def writeLabelsToSqlite
def loadLabelsFromSqlite
def writeSpeedPrototypeToSqlite
def loadSpeedPrototypeFromSqlite
def writeRoutesToSqlite
def loadRoutesFromSqlite
def setRoutes
def setRoadUserTypes
def openCheck
txt files
def readline
def getLines
def writeList
def loadListStrings
def getValuesFromINIFile
def generatePDLaneColumn
def convertTrajectoriesVissimToSqlite
def loadObjectNumbersInLinkFromVissimFile
def loadTrajectoriesFromVissimFile
def selectPDLanes
def countStoppedVehiclesVissim
def countCollisionsVissim
def loadTrajectoriesFromNgsimFile
def convertNgsimFile
def writePositionsToCsv
def writeTrajectoriesToCsv
Variables
string commentChar = '#'
string delimiterChar = '%'
dictionary ngsimUserTypes
tuple suite = doctest.DocFileSuite('tests/storage.txt')
Function Documentation
def storage.convertNgsimFile (inputfile, outputfile, append = False, nObjects = -1, sequenceNum = 0)
Reads data from the trajectory data provided by NGSIM project
and converts to our current format.
References openCheck().
def storage.convertTrajectoriesVissimToSqlite (filename)
Relies on a system call to sqlite3
sqlite3 [file.sqlite] < import_fzp.sql
References openCheck().
def storage.countCollisionsVissim (filename, lanes = None, collisionTimeDifference = 0.2, lowMemory = True)
Counts the number of collisions per lane in a VISSIM trajectory file

To distinguish between cars passing and collision, 
one checks when the sign of the position difference inverts
(if the time are closer than collisionTimeDifference)
If lanes is not None, only the data for the selected lanes will be provided
(format as string x_y where x is link index and y is lane index)
References selectPDLanes().
def storage.countStoppedVehiclesVissim (filename, lanes = None, proportionStationaryTime = 0.7)
Counts the number of vehicles stopped for a long time in a VISSIM trajectory file
and the total number of vehicles

Vehicles are considered finally stationary
if more than proportionStationaryTime of their total time
If lanes is not None, only the data for the selected lanes will be provided
(format as string x_y where x is link index and y is lane index)
References selectPDLanes().
def storage.createBoundingBoxTable (filename, invHomography = None)
Create the table to store the object bounding boxes in image space
References printDBError().
def storage.createIndex (connection, tableName, columnName, unique = False)
Creates an index for the column in the table
I will make querying with a condition on this column faster
References printDBError().
def storage.createIndicatorTables (cursor)
def storage.createInteractionTable (cursor)
def storage.deleteFromSqlite (filename, dataType)
References dropTables().
def storage.dropTables (connection, tableNames)
References printDBError().
def storage.generatePDLaneColumn (data)
def storage.getLines (f, delimiterChar = delimiterChar, commentCharacters = commentChar)
Gets a complete entry (all the lines) in between delimiterChar.
References readline().
def storage.getMinMax (connection, tableName, columnName, minmax)
Returns max/min or both for given column in table
minmax must be string max, min or minmax
References printDBError().
def storage.getNumberRowsTable (connection, tableName, columnName = None)
Returns the number of rows for the table
If columnName is not None, means we want the number of distinct values for that column
(otherwise, we can just count(*))
References printDBError().
def storage.getObjectCriteria (objectNumbers)
def storage.getValuesFromINIFile (filename, option, delimiterChar = '=', commentCharacters = commentChar)
References loadListStrings().
def storage.loadBoundingBoxTableForDisplay (filename)
Loads bounding boxes from bounding_boxes table for display over trajectories
References printDBError().
def storage.loadGroundTruthFromSqlite (filename, gtType = 'bb', gtNumbers = None)
def storage.loadInteractions (filename)
Loads interaction and their indicators

TODO choose the interactions to load
References printDBError().
def storage.loadLabelsFromSqlite (filename)
def storage.loadListStrings (filename, commentCharacters = commentChar)
References getLines(), and openCheck().
def storage.loadObjectNumbersInLinkFromVissimFile (filename, linkIds)
Finds the ids of the objects that go through any of the link in the list linkIds
References printDBError().
def storage.loadPrototypeMatchIndexesFromSqlite (filename)
This function loads the prototypes table in the database of name <filename>.
It returns a list of tuples representing matching ids : [(prototype_id, matched_trajectory_id),...]
References printDBError().
def storage.loadPrototypesFromSqlite (filename)
def storage.loadRoutesFromSqlite (filename)
def storage.loadSpeedPrototypeFromSqlite (filename)
This function loads the prototypes table in the database of name <filename>.
def storage.loadTrajectoriesFromNgsimFile (filename, nObjects = -1, sequenceNum = -1)
Reads data from the trajectory data provided by NGSIM project 
and returns the list of Feature objects
References openCheck(), readline(), and split().
def storage.loadTrajectoriesFromSqlite (filename, trajectoryType, objectNumbers = None, withFeatures = False)
Loads the first objectNumbers objects or the indices in objectNumbers from the database
References getObjectCriteria(), loadTrajectoriesFromTable(), loadUserTypesFromTable(), and printDBError().
def storage.loadTrajectoriesFromTable (connection, tableName, trajectoryType, objectNumbers = None)
Loads trajectories (in the general sense) from the given table
can be positions or velocities

returns a moving object
References getObjectCriteria(), and printDBError().
def storage.loadTrajectoriesFromVissimFile (filename, simulationStepsPerTimeUnit, objectNumbers = None, warmUpLastInstant = None, usePandas = False, nDecimals = 2, lowMemory = True)
Reads data from VISSIM .fzp trajectory file
simulationStepsPerTimeUnit is the number of simulation steps per unit of time used by VISSIM (second)
for example, there seems to be 10 simulation steps per simulated second in VISSIM, 
so simulationStepsPerTimeUnit should be 10, 
so that all times correspond to the number of the simulation step (and can be stored as integers)

Objects positions will be considered only after warmUpLastInstant 
(if the object has no such position, it won't be loaded)

Assumed to be sorted over time
Warning: if reading from SQLite a limited number of objects, objectNumbers will be the maximum object id
References generatePDLaneColumn(), getObjectCriteria(), openCheck(), printDBError(), readline(), and split().
def storage.loadUserTypesFromTable (cursor, trajectoryType, objectNumbers)
References getObjectCriteria().
def storage.openCheck (filename, option = 'r', quitting = False)
txt files
Open file filename in read mode by default
and checks it is open
def storage.printDBError (error)
Sqlite.
def storage.readline (f, commentCharacters = commentChar)
Modified readline function to skip comments
Can take a list of characters or a string (in will work in both)
def storage.readPrototypesFromSqlite (filename)
This function loads the prototype file in the database 
It returns a dictionary for prototypes for each route and nMatching
def storage.saveIndicator (cursor, interactionNum, indicator)
def storage.saveIndicators (filename, interactions, indicatorNames = events.Interaction.indicatorNames)
References createIndicatorTables(), createInteractionTable(), printDBError(), saveIndicator(), and saveInteraction().
def storage.saveInteraction (cursor, interaction)
def storage.saveInteractions (filename, interactions)
References createInteractionTable(), printDBError(), and saveInteraction().
def storage.savePrototypesToSqlite (filename, prototypes, trajectoryType = 'feature')
References printDBError().
def storage.selectPDLanes (data, lanes = None)
Selects the subset of data for the right lanes

Lane format is a string 'x_y' where x is link index and y is lane index
References generatePDLaneColumn().
def storage.setRoadUserTypes (filename, objects)
Saves the user types of the objects in the sqlite database stored in filename
The objects should exist in the objects table
def storage.setRoutes (filename, objects)
def storage.tableExists (filename, tableName)
References printDBError().
def storage.writeFeaturesToSqlite (objects, outputFilename, trajectoryType, objectNumbers = -1)
saving and loading for scene interpretation (Mohamed Gomaa Mohamed's PhD)
write features trajectories maintain trajectory ID,velocities dataset  
def storage.writeLabelsToSqlite (labels, outputFilename)
labels is a dictionary with  keys: routes, values: prototypes Ids
def storage.writeList (filename, l)
References openCheck().
def storage.writePositionsToCsv (f, obj)
def storage.writePrototypesToSqlite (prototypes, nMatching, outputFilename)
prototype dataset is a dictionary with  keys== routes, values== prototypes Ids 
def storage.writeRoutesToSqlite (Routes, outputFilename)
This function writes the activity path define by start and end IDs
def storage.writeSpeedPrototypeToSqlite (prototypes, nmatching, outFilename)
to match the format of second layer prototypes
def storage.writeTrajectoriesToCsv (filename, objects)
References openCheck(), and writePositionsToCsv().
def storage.writeTrajectoriesToSqlite (objects, outputFilename, trajectoryType, objectNumbers = -1)
This function writers trajectories to a specified sqlite file
@param[in] objects -> a list of trajectories
@param[in] trajectoryType -
@param[out] outputFilename -> the .sqlite file containting the written objects
@param[in] objectNumber : number of objects loaded
Variable Documentation
string storage.commentChar = '#'
string storage.delimiterChar = '%'
dictionary storage.ngsimUserTypes
Initial value:
= {'twowheels':1,
                  'car':2,
                  'truck':3}
tuple storage.suite = doctest.DocFileSuite('tests/storage.txt')