polytracktopdtv Namespace Reference
Functions
def zipFolder
def getTypeDict
def extractFrames
def convertDatabase
Variables
tuple parser = argparse.ArgumentParser(description='The program convert polytrack.sqlite database to pdtv bounding boxes', epilog = 'Either the configuration filename or the other parameters (at least video and database filenames) need to be provided.')
tuple args = parser.parse_args()
Function Documentation
def polytracktopdtv.convertDatabase (workDirname, sectionName, sceneFilename = None, databaseFilename = None, videoFilename = None, videoFolderExist = False, firstFrameNum = 0, lastFrameNum = None, cameraCalibrationFilename = None, outputFileName = 'roaduser.json')
Method to convert database from polytrack to PDTV:
workDirname  is the current working directory
sceneFilename is the path to the .cfg file
sectionName is the name of the section we want to process in this file
videoFolderExist specifiy if we want to reextract the video frame or if they already exist at workdir/videoframes/
firstFrameNum is the first frame we want to extract
lastFrameNum is the last frame we want to extract (or None if we want to extract everything)
References extractFrames(), cvutils.getFPS(), getTypeDict(), and zipFolder().
def polytracktopdtv.extractFrames (videoFile, framePath, fps, time, firstFrameNum = 0, lastFrameNum = None)
Method to extract all the frames of the video
References cvutils.getImagesFromVideo().
def polytracktopdtv.getTypeDict (cursor)
Return a dictionnary with integer key and associated type string
i.e.: "0"  -> "unknown"
      "1"  -> "car"
      "2"  -> "pedestrians"
      "3"  -> "motorcycle"
      "4"  -> "bicycle"
      "5"  -> "bus"
      "6"  -> "truck"
      ... and other type if the objects_type table is defined in SQLite
def polytracktopdtv.zipFolder (inputFolder, outputFile)
Method to compress the content of the inputFolder in the outputFile
Variable Documentation
tuple polytracktopdtv.args = parser.parse_args()
tuple polytracktopdtv.parser = argparse.ArgumentParser(description='The program convert polytrack.sqlite database to pdtv bounding boxes', epilog = 'Either the configuration filename or the other parameters (at least video and database filenames) need to be provided.')