Catch Namespace Reference
Namespaces
Detail
Generators
Internal
Matchers
Classes
class NonCopyable
class SafeBool
struct SourceLineInfo
struct Counts
struct Totals
class Ptr
struct IShared
struct SharedImpl
struct IReporterConfig
struct IReporter
struct IReporterFactory
struct IReporterRegistry
struct IConfig
class StreamBufBase
struct IContext
struct IMutableContext
class Context
struct ITestCase
struct ITestCaseRegistry
class MethodTestCase
struct AutoReg
struct ResultWas
struct ResultAction
class ResultInfo
class ResultInfoBuilder
class Expression
class ExpressionBuilder
struct IResultCapture
struct TestFailureException
class ScopedInfo
class Section
struct IGenerator
class BetweenGenerator
class ValuesGenerator
class CompositeGenerator
struct IExceptionTranslator
struct IExceptionTranslatorRegistry
class ExceptionTranslatorRegistrar
class TestCaseInfo
class TestSpec
struct IRunner
Typedefs
typedef void(* TestFunction)()
typedef std::string(* exceptionTranslateFunction)()
Functions
template<typename ContainerT >
void deleteAll (ContainerT &container)
template<typename AssociativeContainerT >
void deleteAllValues (AssociativeContainerT &container)
template<typename ContainerT , typename Function >
void forEach (ContainerT &container, Function function)
template<typename ContainerT , typename Function >
void forEach (const ContainerT &container, Function function)
std::ostream & operator<< (std::ostream &os, const SourceLineInfo &info)
ATTRIBUTE_NORETURN void throwLogicError (const std::string &message, const std::string &file, std::size_t line)
std::string trim (const std::string &str)
IContext & getCurrentContext ()
IMutableContext & getCurrentMutableContext ()
template<typename T >
std::string toString (const T &value)
converts any type to a string
std::string toString (const std::string &value)
std::string toString (const std::wstring &value)
std::string toString (const char *const value)
std::string toString (char *const value)
std::string toString (int value)
std::string toString (unsigned long value)
std::string toString (unsigned int value)
std::string toString (const double value)
std::string toString (bool value)
std::string toString (char value)
std::string toString (signed char value)
bool isTrue (bool value)
template<>
std::string toString< Detail::Approx > (const Detail::Approx &value)
Typedef Documentation
typedef std::string(* Catch::exceptionTranslateFunction)()
typedef void(* Catch::TestFunction)()
Function Documentation
template<typename ContainerT > void Catch::deleteAll (ContainerT & container) [inline]
template<typename AssociativeContainerT > void Catch::deleteAllValues (AssociativeContainerT & container) [inline]
template<typename ContainerT , typename Function > void Catch::forEach (ContainerT & container, Function function) [inline]
template<typename ContainerT , typename Function > void Catch::forEach (const ContainerT & container, Function function) [inline]
IContext& Catch::getCurrentContext ()
IMutableContext& Catch::getCurrentMutableContext ()
bool Catch::isTrue (bool value) [inline]
std::ostream& Catch::operator<< (std::ostream & os, const SourceLineInfo & info) [inline]
References Catch::SourceLineInfo::file, and Catch::SourceLineInfo::line.
ATTRIBUTE_NORETURN void Catch::throwLogicError (const std::string & message, const std::string & file, std::size_t line) [inline]
template<typename T > std::string Catch::toString (const T & value)
converts any type to a string
The default template forwards on to ostringstream - except when an ostringstream overload does not exist - in which case it attempts to detect that and writes {?}. Overload (not specialise) this template for custom typs that you don't want to provide an ostream overload for.
References Catch::Detail::makeString().
std::string Catch::toString (const std::string & value) [inline]
std::string Catch::toString (const std::wstring & value) [inline]
std::string Catch::toString (const char *const value) [inline]
References toString().
std::string Catch::toString (char *const value) [inline]
References toString().
std::string Catch::toString (int value) [inline]
std::string Catch::toString (unsigned long value) [inline]
std::string Catch::toString (unsigned int value) [inline]
References toString().
std::string Catch::toString (const double value) [inline]
std::string Catch::toString (bool value) [inline]
std::string Catch::toString (char value) [inline]
References Catch::Detail::makeString(), and toString().
std::string Catch::toString (signed char value) [inline]
References toString().
template<> std::string Catch::toString< Detail::Approx > (const Detail::Approx & value) [inline]
std::string Catch::trim (const std::string & str) [inline]