objectsmoothing Namespace Reference
Functions
def findNearest
def getFeatures
def buildFeature
def getBearing
def computeVelocities
def computeAcceleration
def computeJerk
def sumSquaredJerk
def smoothObjectTrajectory
def smoothObject
Function Documentation
def objectsmoothing.buildFeature (obj, featureID, num = 1)
References getFeatures().
def objectsmoothing.computeAcceleration (obj, fromPosition = True)
References computeVelocities().
def objectsmoothing.computeJerk (obj, fromPosition = True)
References computeAcceleration().
def objectsmoothing.computeVelocities (obj, smoothing = True, halfWidth = 3)
References utils.filterMovingWindow().
def objectsmoothing.findNearest (feat, featureSet, t, reverse = True)
References moving.Point.distanceNorm2().
def objectsmoothing.getBearing (p1, p2, p3)
References moving.Point.distanceNorm2().
def objectsmoothing.getFeatures (obj, featureID)
References findNearest().
def objectsmoothing.smoothObject (obj, newNum, minLengthParam = 0.7, smoothing = False, plotResults = True, halfWidth = 3, _computeVelocities = True, optimize = True, create = False)
Computes a smoother trajectory for the object
and optionnally smoother velocities

The object should have its features in obj.features
TODO: check whether features are necessary
References utils.argmaxDict(), computeVelocities(), smoothObjectTrajectory(), and sumSquaredJerk().
def objectsmoothing.smoothObjectTrajectory (obj, featureID, newNum, smoothing = False, halfWidth = 3, create = False)
References buildFeature(), utils.filterMovingWindow(), and getBearing().
def objectsmoothing.sumSquaredJerk (obj, fromPosition = True)
References computeJerk().