c/test_graph.cpp File Reference
#include `Motion.hpp`
*
#include `testutils.hpp`
*
#include `opencv2/core/core.hpp`
*
#include `catch.hpp`
*
#include <iostream>
*
Functions
TEST_CASE (`graph/connected_components`,`test graph connected components`)
Function Documentation
TEST_CASE (`graph/connected_components` , `test graph connected components`)
References FeatureGraph::addFeature(), FeatureGraph::connectedComponents(), createFeatureTrajectory(), FeatureGraph::getFeatureGroups(), FeatureGraph::getNEdges(), FeatureGraph::getNVertices(), REQUIRE, and REQUIRE_FALSE.