include/utils.hpp File Reference
#include <sstream>
*
#include <iosfwd>
*
#include <string>
*
#include <vector>
*
Functions
std::vector< std::vector< float > > loadNumbers (const std::string &filename, const std::string &separator=::separator)
std::string getlineComment (std::ifstream &f)
int toInt (const std::string &s)
float toFloat (const std::string &s)
double toDouble (const std::string &s)
void openWriteScientificPrecision (std::ofstream &out, const std::string &filename, const int &precision)
void openWritePrecision (std::ofstream &out, const std::string &filename, const int &precision)
bool openCheck (std::ifstream &f, const std::string &filename, const std::string &callingFunctionName)
bool openCheck (std::ofstream &f, const std::string &filename, const std::string &callingFunctionName)
double square (const int &a)
bool forwardKey (const int &pressedKey)
bool backwardKey (const int &pressedKey)
bool saveKey (const int &pressedKey)
bool interruptionKey (const int &pressedKey)
bool skipKey (const int &pressedKey)
template<class Seq >
void split (Seq &result, const std::string &text, const std::string &separator=::separator)
template<typename T >
bool fromString (T &result, const std::string &s)
Variables
const char commentChar = '#'
Function Documentation
bool backwardKey (const int & pressedKey) [inline]
bool forwardKey (const int & pressedKey) [inline]
Implements key bindings, for example for cvWaitKey().
template<typename T > bool fromString (T & result, const std::string & s)
Converts strings to numbers.
std::string getlineComment (std::ifstream & f)
Gets line in a file, skipping comments (starting with '#') (wrapper around getline). Warning: returns an empty string if all the lines to the end of the file are comments.
References commentChar.
bool interruptionKey (const int & pressedKey) [inline]
std::vector<std::vector<float> > loadNumbers (const std::string & filename, const std::string & separator = ::separator)
Loads lines of numbers from a text file, separated by some character
References getlineComment(), openCheck(), split(), and toFloat().
bool openCheck (std::ifstream & f, const std::string & filename, const std::string & callingFunctionName)
Opens files and checks how it went.
bool openCheck (std::ofstream & f, const std::string & filename, const std::string & callingFunctionName)
void openWritePrecision (std::ofstream & out, const std::string & filename, const int & precision)
References openCheck().
void openWriteScientificPrecision (std::ofstream & out, const std::string & filename, const int & precision)
Opens file for writing with fixed scientific precision.
References openWritePrecision().
bool saveKey (const int & pressedKey) [inline]
bool skipKey (const int & pressedKey) [inline]
template<class Seq > void split (Seq & result, const std::string & text, const std::string & separator = ::separator) [inline]
Splits a string on the separator. The resulting string items are added to the result (the list is not cleared).
double square (const int & a) [inline]
double toDouble (const std::string & s)
Converts a string to a double.
References fromString().
float toFloat (const std::string & s)
Converts a string to a float.
References fromString().
int toInt (const std::string & s)
Converts a string to an integer.
References fromString().
Variable Documentation
const char commentChar = '#'