c/utils.cpp File Reference
#include `utils.hpp`
*
#include <boost/foreach.hpp>
*
#include <iostream>
*
#include <fstream>
*
Functions
std::vector< std::vector< float > > loadNumbers (const string &filename, const string &separator)
int toInt (const std::string &s)
float toFloat (const std::string &s)
double toDouble (const std::string &s)
string getlineComment (ifstream &f)
void openWriteScientificPrecision (ofstream &out, const string &filename, const int &precision)
void openWritePrecision (ofstream &out, const string &filename, const int &precision)
bool openCheck (ifstream &f, const string &filename, const string &callingFunctionName)
bool openCheck (ofstream &f, const string &filename, const string &callingFunctionName)
Function Documentation
string getlineComment (std::ifstream & f)
Gets line in a file, skipping comments (starting with '#') (wrapper around getline). Warning: returns an empty string if all the lines to the end of the file are comments.
References commentChar.
std::vector<std::vector<float> > loadNumbers (const std::string & filename, const std::string & separator = ::separator)
Loads lines of numbers from a text file, separated by some character
References getlineComment(), openCheck(), split(), and toFloat().
bool openCheck (std::ifstream & f, const std::string & filename, const std::string & callingFunctionName)
Opens files and checks how it went.
bool openCheck (ofstream & f, const string & filename, const string & callingFunctionName)
void openWritePrecision (ofstream & out, const string & filename, const int & precision)
References openCheck().
void openWriteScientificPrecision (std::ofstream & out, const std::string & filename, const int & precision)
Opens file for writing with fixed scientific precision.
References openWritePrecision().
double toDouble (const std::string & s)
Converts a string to a double.
References fromString().
float toFloat (const std::string & s)
Converts a string to a float.
References fromString().
int toInt (const std::string & s)
Converts a string to an integer.
References fromString().